name: bcd_me
channels:
  - conda-forge
dependencies:
  - xarray>=2025.1.1
  - numpy
  - xagg
  - pandas
  - geopandas >= 0.12.0
  - xesmf >= 0.7.1
  - scipy
  - cmocean
  - matplotlib
  - seaborn
  - cartopy
  - tqdm
  - jupyterlab
  - dask>=3
  - ipywidgets
  - jupyterlab_widgets
  - nc-time-axis
  - zarr
  - geoutils
  - numba
  - flox # faster xarray groupby
  # For earthmover
  - pooch
  - arraylake
